Repository LBHackney-IT/lbh-social-care-frontend, pull requests merged in 2021-06, with the labels that each got.

#426 Form/face overview
  data/flexibleForms/allForms.ts
  data/flexibleForms/faceOverview.ts
  data/flexibleForms/forms.types.ts
  data/flexibleForms/index.ts
Labels: enhancement

#428 clean up form layout a 'lil
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/steps/[stepId].tsx
Labels: enhancement

#439 Undo change to reviewNotes component in review form step
  data/forms/warning-note-review.tsx
  types.ts
Labels: bug, managing workloads

#443 Fix(SCT-461): Add missing date validation when creating/reviewing a warning note
  data/forms/warning-note-review.tsx
  data/forms/warning-note.tsx
Labels: enhancement

#444 feature(SCT-489): improved messaging for add new people
  components/Form/AddressLookup/AddressLookup.tsx
  components/Search/Search.jsx
  components/Search/Search.module.scss
  components/Search/results/ResidentsTable.module.scss
  components/Search/results/ResidentsTable.spec.tsx
  components/Search/results/ResidentsTable.tsx
  components/Search/results/__snapshots__/ResidentsTable.spec.tsx.snap
  cypress/integration/search_for_person.ts
  data/forms/create-new-person.tsx
  pages/people/add/[[...stepId]].tsx
Labels: enhancement

#446 Fix(SCT-492): Add missing "s" in URL path when saving a form
  components/FormWizard/FormWizard.jsx
Labels: bug

#447 Fix(SCT-461): Add missing date validation for Date Informed form component
  data/forms/warning-note.tsx
Labels: enhancement, managing workloads

#448 update review3c content
  data/flexibleForms/review3C.ts
Labels: assessing and recording

#456 use a more appropriate default error message
  components/AllocatedCases/MyAllocatedCases.spec.tsx
  components/AllocatedCases/__snapshots__/MyAllocatedCases.spec.tsx.snap
  components/Cases/CaseRecap/__snapshots__/HistoricVisit.spec.tsx.snap
  components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap
  components/ErrorMessage/ErrorMessage.tsx
  components/ErrorMessage/__snapshots__/ErrorMessage.spec.tsx.snap
  components/Form/FieldErrorMessage/FieldErrorMessage.spec.tsx
  components/Search/Search.spec.jsx
  components/WorkerView/__snapshots__/WorkerSearch.spec.tsx.snap
Labels: enhancement

#457 Improve add person flow
  components/DuplicateWarningPanel/DuplicateWarningPanel.module.scss
  components/DuplicateWarningPanel/DuplicateWarningPanel.spec.tsx
  components/DuplicateWarningPanel/DuplicateWarningPanel.tsx
  components/Search/Search.jsx
  components/Steps/Summary.tsx
  pages/people/add/[[...stepId]].tsx
  utils/urls.ts
Labels: assessing and recording, enhancement

#455 Feature/footer
  components/Layout/Footer/Footer.module.scss
  components/Layout/Footer/Footer.tsx
  components/Layout/__snapshots__/index.spec.tsx.snap
  components/Layout/index.tsx
Labels: enhancement, feature

#461 add confirmation banner component
  components/ConfirmationBanner/ConfirmationBanner.module.scss
  components/ConfirmationBanner/ConfirmationBanner.spec.tsx
  components/ConfirmationBanner/ConfirmationBanner.stories.tsx
  components/ConfirmationBanner/ConfirmationBanner.tsx
  components/Icons/TickCircle.tsx
Labels: enhancement

#435 make it easier to get a resident by id
  lib/residents.spec.ts
  lib/residents.ts
  pages/api/residents/[id]/index.ts
  pages/api/submissions/[id]/index.ts
  pages/api/submissions/[id]/steps/[stepId].tsx
Labels: enhancement

#341 add flexible answers component
  components/Cases/CaseRecap/CaseNote.tsx
  components/FlexibleAnswers/FlexibleAnswers.spec.tsx
  components/FlexibleAnswers/FlexibleAnswers.stories.tsx
  components/FlexibleAnswers/FlexibleAnswers.tsx
  components/TaskList/TaskListHeader.spec.tsx
  components/TaskList/TaskListHeader.tsx
  data/flexibleForms/forms.types.ts
  pages/people/[id]/submissions/[submissionId].tsx
Labels: assessing and recording, feature

#462 Fix/open residents in new tab when adding
  components/DuplicateWarningPanel/DuplicateWarningPanel.tsx
  components/Search/results/ResidentsTable.tsx
Labels: bug

#465 lil' hotfix
  pages/people/[id]/submissions/[submissionId].tsx
Labels: bug

#430 Feature/real api routes for submissions
  data/flexibleForms/forms.types.ts
  data/flexibleForms/review3C.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  pages/api/submissions/[id]/index.ts
  pages/api/submissions/[id]/steps/[stepId].tsx
  pages/api/submissions/index.ts
  pages/people/[id]/submissions/[submissionId].tsx
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/steps/[stepId].tsx
  pages/submissions/new.tsx
Labels: assessing and recording, feature

#468 it works and we love that it works
  data/flexibleForms/allForms.ts
  data/flexibleForms/forms.types.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  pages/api/submissions/[id]/index.ts
  pages/people/[id]/submissions/[submissionId].tsx
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/steps/[stepId].tsx
Labels: assessing and recording, feature

#471 css tweaks to get forms looking their best
  stylesheets/all.scss
Labels: assessing and recording, bug, enhancement

#473 make submission api route code more readable
  pages/api/submissions/[id]/index.ts
  pages/api/submissions/[id]/steps/[stepId].tsx
Labels: assessing and recording, enhancement

#431 Autosave
  components/FlexibleForms/StepForm.spec.tsx
  components/FlexibleForms/StepForm.tsx
  contexts/Autosave.module.scss
  contexts/autosaveContext.spec.tsx
  contexts/autosaveContext.tsx
  hooks/useWarnUnsavedChanges.ts
  pages/submissions/[id]/steps/[stepId].tsx
  public/spinner.svg
Labels: assessing and recording, feature

#480 Fix/refactor step form continue function
  components/FlexibleForms/StepForm.spec.tsx
  components/FlexibleForms/StepForm.tsx
Labels: assessing and recording, bug

#484 show submissions in records table
  components/Cases/CaseLink.spec.tsx
  components/Cases/CaseLink.tsx
  components/Cases/Cases.spec.tsx
  components/Cases/Cases.tsx
  components/Cases/CasesTable.tsx
  components/Cases/__snapshots__/CaseLink.spec.tsx.snap
  components/Cases/__snapshots__/Cases.spec.tsx.snap
  components/Cases/__snapshots__/CasesTable.spec.tsx.snap
  components/Search/Search.spec.jsx
Labels: assessing and recording, feature

#482 clean up form config for launch
  data/flexibleForms/allForms.ts
  data/flexibleForms/index.ts
  data/flexibleForms/review3C.ts
Labels: assessing and recording, enhancement

#486 new submission page auto-submits when the right data is in the url
  pages/submissions/new.tsx
Labels: assessing and recording, feature

#491 Feature/conditional fields can be required
  components/FlexibleForms/StepForm.tsx
  lib/validators.spec.ts
  lib/validators.ts
Labels: assessing and recording, enhancement

#493 flexible form cleanup and bug fixes
  components/FlexibleForms/StepForm.tsx
Labels: assessing and recording, bug

#499 fix/weird top margin
  stylesheets/all.scss
Labels: bug

#495 show unfinished submissions on dashboad
  components/Dashboard/DashboardWrapper.tsx
  components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap
  components/SaveFormData/SaveFormData.spec.tsx
  components/SaveFormData/SaveFormData.tsx
  components/SaveFormData/__snapshots__/SaveFormData.spec.tsx.snap
  components/SubmissionsTable/Filter.spec.tsx
  components/SubmissionsTable/Filter.tsx
  components/SubmissionsTable/SearchBox.spec.tsx
  components/SubmissionsTable/SearchBox.tsx
  components/SubmissionsTable/SubmissionRow.spec.tsx
  components/SubmissionsTable/SubmissionRow.tsx
  components/SubmissionsTable/index.module.scss
  components/SubmissionsTable/index.spec.tsx
  components/SubmissionsTable/index.tsx
  data/flexibleForms/forms.types.ts
  factories/submissions.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  pages/forms-in-progress.tsx
  tsconfig.json
Labels: assessing and recording, feature, managing workloads

#487 launch the new review 3c form!
  components/AddForm/AddForm.tsx
  data/googleForms/adultForms.ts
Labels: assessing and recording, feature

#504 feature/only return submissions from current service on dashboard
  components/SubmissionsTable/index.spec.tsx
  components/SubmissionsTable/index.tsx
  lib/submissions.spec.ts
  lib/submissions.ts
  pages/forms-in-progress.tsx
  types.ts
Labels: assessing and recording, enhancement

#501 fix/adding a new submission
  components/AddForm/AddForm.tsx
Labels: bug

#498 Feature/timetable question
  components/FlexibleAnswers/FlexibleAnswers.module.scss
  components/FlexibleAnswers/FlexibleAnswers.tsx
  components/FlexibleAnswers/TimetableAnswer.spec.tsx
  components/FlexibleAnswers/TimetableAnswer.tsx
  components/FlexibleForms/FlexibleFields.tsx
  components/FlexibleForms/StepForm.tsx
  components/FlexibleForms/TimetableField.module.scss
  components/FlexibleForms/TimetableField.spec.tsx
  components/FlexibleForms/TimetableField.tsx
  data/flexibleForms/forms.types.ts
  data/flexibleForms/review3C.ts
  lib/utils.spec.ts
  lib/utils.ts
  lib/validators.spec.ts
  lib/validators.ts
Labels: assessing and recording, feature
