Repository LBHackney-IT/lbh-social-care-frontend, pull requests merged in 2021-07, with the labels that each got.

#522 Feature/tag input
  components/Cases/CaseLink.spec.tsx
  components/Cases/__snapshots__/CaseLink.spec.tsx.snap
  components/FlexibleForms/ComboboxField.module.scss
  components/FlexibleForms/FlexibleFields.tsx
  components/FlexibleForms/TagsField.spec.tsx
  components/FlexibleForms/TagsField.tsx
  data/caseNoteTags.ts
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  data/flexibleForms/index.ts
  lib/utils.ts
  lib/validators.ts
Labels: assessing and recording, enhancement, feature

#500 make the app wider
  stylesheets/all.scss
Labels: enhancement

#531 fix: types
  components/Layout/BackButton/BackButton.spec.tsx
  lib/validators.ts
Labels: bug

#506 Feature/proper client search
  components/SubmissionsTable/index.tsx
  hooks/useSearch.spec.tsx
  hooks/useSearch.ts
  package.json
Labels: assessing and recording, feature, managing workloads

#533 feature: improve face overview form
  data/flexibleForms/faceOverview.ts
Labels: assessing and recording, enhancement

#534 feature: discard submissions
  components/Dialog/Dialog.spec.tsx
  components/Dialog/Dialog.tsx
  components/Modal/Modal.module.scss
  components/Modal/Modal.spec.tsx
  components/Modal/Modal.stories.tsx
  components/Modal/Modal.tsx
  components/Modal/__snapshots__/Modal.spec.tsx.snap
  components/SubmissionsTable/DiscardDialog.module.scss
  components/SubmissionsTable/DiscardDialog.spec.tsx
  components/SubmissionsTable/DiscardDialog.tsx
  components/SubmissionsTable/SubmissionRow.tsx
  components/SubmissionsTable/index.tsx
  data/flexibleForms/forms.types.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  package.json
  pages/api/submissions/[id]/index.ts
  stylesheets/all.scss
Labels: assessing and recording, feature

#460 Feat(SCT-329): Group recording
  components/Dialog/Dialog.test.tsx
  components/Dialog/Dialog.tsx
  components/GroupRecording/GroupRecordingWidget.module.scss
  components/GroupRecording/GroupRecordingWidget.spec.tsx
  components/GroupRecording/GroupRecordingWidget.tsx
  components/GroupRecording/__snapshots__/GroupRecordingWidget.spec.tsx.snap
  components/PersonSelect/PersonSelect.module.scss
  components/PersonSelect/PersonSelect.spec.tsx
  components/PersonSelect/PersonSelect.tsx
  components/PersonSelect/__snapshots__/PersonSelect.spec.tsx.snap
  components/PersonWidget/PersonWidget.module.scss
  components/PersonWidget/PersonWidget.spec.tsx
  components/PersonWidget/PersonWidget.tsx
  components/Search/results/__snapshots__/RelationshipTable.spec.tsx.snap
  components/Search/results/__snapshots__/ResidentsTable.spec.tsx.snap
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/forms.types.ts
  data/flexibleForms/index.ts
  factories/residents.ts
  jest.config.js
  lib/feature-flags/feature-flags.tsx
  lib/submissions.spec.ts
  lib/submissions.ts
  package.json
  pages/api/submissions/[id]/index.ts
  pages/people/[id]/submissions/[submissionId].tsx
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/steps/[stepId].tsx
  types.ts
  yarn.lock
Labels: assessing and recording, feature

#536 feat(SCT-538): Add safeguard adult manager decision form
  data/flexibleForms/index.ts
  data/flexibleForms/sgAdultManagerDecisionConcern.ts
Labels: assessing and recording, feature

#538 Feat(SCT-739): Add feature flag typescript helper function
  .github/CONTRIBUTING.md
  features.ts
  lib/feature-flags/feature-flags.spec.tsx
  lib/feature-flags/feature-flags.tsx
  pages/_app.tsx
Labels: feature, managing workloads

#545 feat: add redirects
  pages/people/[id]/submissions/[submissionId].tsx
Labels: assessing and recording, bug, enhancement

#537 feat(sct-330): approve submissions
  components/ApprovalWidget/ApprovalWidget.module.scss
  components/ApprovalWidget/ApprovalWidget.spec.tsx
  components/ApprovalWidget/ApprovalWidget.tsx
  components/ApprovalWidget/ApproveDialog.spec.tsx
  components/ApprovalWidget/ApproveDialog.tsx
  components/ApprovalWidget/RejectDialog.spec.tsx
  components/ApprovalWidget/RejectDialog.tsx
  components/SubmissionsTable/index.spec.tsx
  components/TaskList/TaskListHeader.spec.tsx
  components/TaskList/TaskListHeader.tsx
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  factories/submissions.ts
  lib/notify.spec.ts
  lib/notify.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  lib/validators.ts
  notify.d.ts
  package.json
  pages/api/submissions/[id]/approvals.ts
  pages/api/submissions/[id]/index.ts
  pages/people/[id]/submissions/[submissionId].tsx
  pages/submissions/[id]/index.tsx
  stylesheets/all.scss
  yarn.lock
Labels: assessing and recording, feature

#546 feat(sct-802): revision timeline
  components/RevisionTimeline/MiniRevisionTimeline.module.scss
  components/RevisionTimeline/MiniRevisionTimeline.tsx
  components/RevisionTimeline/MiniSubmissionTimeline.spec.tsx
  components/RevisionTimeline/RevisionTimeline.spec.tsx
  components/RevisionTimeline/RevisionTimeline.tsx
  components/SubmissionsTable/SubmissionRow.tsx
  components/SubmissionsTable/index.module.scss
  data/flexibleForms/forms.types.ts
  pages/people/[id]/submissions/[submissionId].tsx
Labels: assessing and recording, feature

#553 fix: only autofill google urls
  components/AddForm/AddForm.tsx
Labels: assessing and recording, bug

#549 feat(SCT-827): printable versions of forms
  components/Layout/index.spec.tsx
  components/Layout/index.tsx
  components/PrintableForm/PrintableForm.module.scss
  components/PrintableForm/PrintableForm.spec.tsx
  components/PrintableForm/PrintableForm.tsx
  pages/_app.tsx
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/printable.tsx
Labels: assessing and recording, feature

#559 feat(SCT-814): overhaul person view
  components/Cases/CaseLink.tsx
  components/Dialog/Dialog.test.tsx
  components/NewPersonView/Event.spec.tsx
  components/NewPersonView/Event.tsx
  components/NewPersonView/FilterButton.spec.tsx
  components/NewPersonView/FilterButton.tsx
  components/NewPersonView/Layout.spec.tsx
  components/NewPersonView/Layout.tsx
  components/NewPersonView/PersonTimeline.spec.tsx
  components/NewPersonView/PersonTimeline.tsx
  components/NewPersonView/UnfinishedSubmissions.spec.tsx
  components/NewPersonView/UnfinishedSubmissions.tsx
  components/NewPersonView/index.module.scss
  components/PersonView/PersonDetails.spec.tsx
  components/PersonView/PersonDetails.tsx
  components/PersonView/__snapshots__/PersonDetails.spec.tsx.snap
  components/SubmissionsTable/SearchBox.tsx
  components/WarningNote/WarningNotes.tsx
  components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap
  components/pages/people/PersonDetailsPage.spec.tsx
  components/pages/people/PersonDetailsPage.tsx
  components/pages/people/__snapshots__/PersonDetailsPage.spec.tsx.snap
  components/pages/people/relationships/view/Relationships.tsx
  cypress/integration/add_record.ts
  cypress/integration/allocate_worker.ts
  cypress/integration/view_person.ts
  cypress/integration/view_warning_note_details.ts
  data/flexibleForms/forms.types.ts
  data/minorForms.ts
  features.ts
  pages/api/submissions/index.ts
  pages/people/[id]/allocations.tsx
  pages/people/[id]/details.tsx
  pages/people/[id]/index.tsx
  pages/people/[id]/relationships.tsx
  utils/api/submissions.spec.ts
  utils/api/submissions.ts
  utils/date.spec.ts
  utils/date.ts
Labels: assessing and recording, feature, understanding residents

#568 chore: update person details
  components/PersonView/PersonDetails.module.scss
  components/PersonView/PersonDetails.spec.tsx
  components/PersonView/PersonDetails.tsx
  components/PersonView/PersonView.spec.tsx
  components/PersonView/PersonView.tsx
  components/PersonView/__snapshots__/PersonDetails.spec.tsx.snap
  cypress/integration/add_record.ts
  cypress/integration/view_warning_note_details.ts
Labels: enhancement, understanding residents

#573 chore(sct-814): fix allocations layout
  components/AllocatedWorkers/AllocatedWorkers.spec.tsx
  components/AllocatedWorkers/AllocatedWorkers.tsx
  components/AllocatedWorkers/AllocatedWorkersTable.tsx
  components/AllocatedWorkers/__snapshots__/AllocatedWorkersTable.spec.tsx.snap
  components/PersonView/PersonDetails.tsx
  cypress/integration/allocate_worker.ts
  cypress/integration/view_person.ts
  stylesheets/Section.module.scss
Labels: enhancement, managing workloads, understanding residents

#564 feat(SCT-829): overhaul adding a form
  components/AddForm/AddForm.spec.tsx
  components/AddForm/AddForm.tsx
  components/AddForm/__snapshots__/AddForm.spec.tsx.snap
  components/AddFormDialog/AddFormDialog.module.scss
  components/AddFormDialog/AddFormDialog.spec.tsx
  components/AddFormDialog/AddFormDialog.tsx
  components/NewPersonView/Layout.tsx
  cypress/integration/add_record.ts
  hooks/useSearch.spec.tsx
  hooks/useSearch.ts
  pages/people/[id]/records/index.tsx
  utils/populate.ts
Labels: assessing and recording, feature, understanding residents

#578 chore(sct-858): fix error when there are no events on the timeline
  components/NewPersonView/PersonTimeline.spec.tsx
  components/NewPersonView/PersonTimeline.tsx
  components/NewPersonView/index.module.scss
Labels: bug, understanding residents

#574 feat(sct-855): overhaul dashboard nav
  components/Dashboard/DashboardWrapper.module.scss
  components/Dashboard/DashboardWrapper.tsx
  components/Dashboard/MyData.module.scss
  components/Dashboard/MyData.spec.tsx
  components/Dashboard/MyData.tsx
  components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap
  components/Dashboard/__snapshots__/MyData.spec.tsx.snap
  components/Layout/Header/Header.spec.tsx
  components/Layout/Header/Header.tsx
  components/Layout/Header/__snapshots__/Header.spec.tsx.snap
  components/NewPersonView/Layout.tsx
  components/NewPersonView/index.module.scss
  components/Search/__snapshots__/MainSearchWrapper.spec.tsx.snap
  components/SubmissionsTable/index.module.scss
  components/Tabs/Tabs.module.scss
  components/Tabs/Tabs.tsx
  components/Tabs/__snapshots__/Tabs.spec.tsx.snap
  pages/forms-in-progress.tsx
  pages/index.tsx
  pages/my-records.tsx
Labels: assessing and recording, enhancement, managing workloads

#579 feat: flip major <-> minor events on timeline
  components/NewPersonView/FilterButton.spec.tsx
  components/NewPersonView/FilterButton.tsx
  components/NewPersonView/PersonTimeline.tsx
  data/majorForms.ts
Labels: enhancement, understanding residents

#581 chore(sct-823): clean up and fix child case note
  components/FlexibleAnswers/FlexibleAnswers.tsx
  components/FlexibleForms/ComboboxField.tsx
  components/FlexibleForms/FlexibleFields.tsx
  components/FlexibleForms/TagsField.spec.tsx
  components/FlexibleForms/TagsField.tsx
  components/PrintableForm/PrintableForm.tsx
  data/caseNoteTags.ts
  data/cfsCaseNoteTypes.ts
  data/cfsServiceAreas.ts
  data/childCaseNoteTags.ts
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  data/forms/cfs-case-notes-recording.tsx
  data/forms/index.tsx
  lib/utils.spec.ts
  lib/utils.ts
  lib/validators.ts
  pages/api/submissions/[id]/index.ts
  pages/people/[id]/records/case-notes-recording/[[...stepId]].tsx
  stylesheets/all.scss
Labels: assessing and recording, bug, enhancement

#571 feat(SCT-823): no task list if single step form
  components/FlexibleAnswers/FlexibleAnswers.spec.tsx
  components/FlexibleAnswers/FlexibleAnswers.tsx
  components/FlexibleForms/StepForm.spec.tsx
  components/FlexibleForms/StepForm.tsx
  components/GroupRecording/GroupRecordingWidget.spec.tsx
  components/GroupRecording/GroupRecordingWidget.tsx
  components/NewPersonView/Layout.tsx
  data/flexibleForms/index.ts
  lib/submissions.ts
  pages/api/case-note/[id].ts
  pages/api/submissions/[id]/index.ts
  pages/api/submissions/[id]/steps/[stepId].tsx
  pages/people/[id]/case-note.tsx
  pages/submissions/[id]/index.tsx
  pages/submissions/[id]/steps/[stepId].tsx
Labels: assessing and recording, enhancement

#589 fix: remove dead button
  components/Cases/Cases.tsx
  components/Cases/__snapshots__/Cases.spec.tsx.snap
Labels: assessing and recording, bug

#590 add canonical urls to forms
  components/AddFormDialog/AddFormDialog.spec.tsx
  components/AddFormDialog/AddFormDialog.tsx
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/forms.types.ts
Labels: assessing and recording, enhancement

#593 fix: don't prematurely launch cfs case notes
  components/NewPersonView/Layout.tsx
Labels: assessing and recording

#592 feat(SCT-519): activate child case notes
  components/Cases/CaseLink.spec.tsx
  components/Cases/CaseLink.tsx
  components/Cases/__snapshots__/CaseLink.spec.tsx.snap
  components/FlexibleForms/TagsField.spec.tsx
  components/GroupRecording/GroupRecordingWidget.tsx
  components/NewPersonView/Event.tsx
  components/NewPersonView/Layout.spec.tsx
  components/NewPersonView/Layout.tsx
  cypress/integration/add_record.ts
  data/childCaseNoteTags.ts
  data/flexibleForms/childCaseNote.ts
  data/googleForms/childForms.ts
  stylesheets/all.scss
Labels: assessing and recording, feature

#598 fix: case note submit bug
  pages/people/[id]/case-note.tsx
Labels: assessing and recording, bug

#599 chore(SCT-519): overhaul asc case notes
  components/AddFormDialog/AddFormDialog.spec.tsx
  components/NewPersonView/Layout.spec.tsx
  components/NewPersonView/Layout.tsx
  data/flexibleForms/adultCaseNote.ts
  data/flexibleForms/index.ts
  pages/people/[id]/case-note.tsx
  pages/people/[id]/records/case-notes-recording/[[...stepId]].tsx
Labels: assessing and recording, enhancement

#603 feat: mark preview forms
  components/AddFormDialog/AddFormDialog.spec.tsx
  components/AddFormDialog/AddFormDialog.tsx
Labels: assessing and recording, enhancement

#588 feat(SCT-844): Add panel approval
  components/ApprovalWidget/PanelApprovalWidget.spec.tsx
  components/ApprovalWidget/PanelApprovalWidget.tsx
  components/ApprovalWidget/PanelApproveDialog.tsx
  components/ApprovalWidget/PanelApproveDialogue.spec.tsx
  components/ApprovalWidget/RejectDialog.tsx
  components/RevisionTimeline/RevisionTimeline.spec.tsx
  components/RevisionTimeline/RevisionTimeline.tsx
  components/TaskList/TaskListHeader.spec.tsx
  components/TaskList/TaskListHeader.tsx
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  factories/submissions.ts
  lib/submissions.spec.ts
  lib/submissions.ts
  lib/validators.spec.ts
  lib/validators.ts
  pages/api/submissions/[id]/panel-approvals.ts
  pages/people/[id]/submissions/[submissionId].tsx
Labels: assessing and recording, feature

#611 fix: formats dates correctly in the timeline view
  components/NewPersonView/Event.tsx
  components/NewPersonView/PersonTimeline.tsx
Labels: bug, understanding residents

#605 feat: datetime field
  components/FlexibleForms/DateTimeField.module.scss
  components/FlexibleForms/DateTimeField.spec.tsx
  components/FlexibleForms/DateTimeField.tsx
  components/FlexibleForms/FlexibleFields.spec.tsx
  components/FlexibleForms/FlexibleFields.tsx
  components/FlexibleForms/StepForm.tsx
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  lib/utils.spec.ts
  lib/utils.ts
  lib/validators.spec.ts
  lib/validators.ts
  stylesheets/all.scss
Labels: assessing and recording, feature

#616 feat: bring back google form prefilling
  components/AddFormDialog/AddFormDialog.spec.tsx
  components/AddFormDialog/AddFormDialog.tsx
  utils/populate.spec.ts
  utils/populate.ts
Labels: assessing and recording, enhancement

#614 feat(SCT-918): timeline improvements
  components/Cases/CaseLink.tsx
  components/NewPersonView/Event.spec.tsx
  components/NewPersonView/Event.tsx
  components/NewPersonView/EventLink.spec.tsx
  components/NewPersonView/EventLink.tsx
  components/NewPersonView/Layout.spec.tsx
  components/NewPersonView/Layout.tsx
  components/NewPersonView/PersonTimeline.tsx
  components/NewPersonView/index.module.scss
  utils/date.spec.ts
  utils/date.ts
  utils/urls.spec.ts
  utils/urls.ts
Labels: assessing and recording, enhancement, understanding residents

#618 fix: person view appearance tweaks
  components/NewPersonView/Layout.tsx
  components/PersonView/PersonDetails.tsx
  components/RevisionTimeline/MiniRevisionTimeline.tsx
  components/RevisionTimeline/RevisionTimeline.tsx
  components/SubmissionsTable/SubmissionRow.tsx
  components/pages/people/relationships/view/Relationships.tsx
  stylesheets/Section.module.scss
  stylesheets/all.scss
Labels: enhancement, understanding residents

#619 feat: refactor submission components
  components/Cases/CaseLink.tsx
  components/Dashboard/DashboardWrapper.tsx
  components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap
  components/Dialog/Dialog.tsx
  components/NewPersonView/Event.tsx
  components/NewPersonView/index.module.scss
  components/RevisionTimeline/MiniRevisionTimeline.tsx
  components/RevisionTimeline/MiniSubmissionTimeline.spec.tsx
  components/Search/Search.jsx
  components/SubmissionsTable/Filter.spec.tsx
  components/SubmissionsTable/Filter.tsx
  components/SubmissionsTable/SubmissionDetailDialog.spec.tsx
  components/SubmissionsTable/SubmissionDetailDialog.tsx
  components/SubmissionsTable/SubmissionPanel.spec.tsx
  components/SubmissionsTable/SubmissionPanel.tsx
  components/SubmissionsTable/SubmissionRow.spec.tsx
  components/SubmissionsTable/SubmissionRow.tsx
  components/SubmissionsTable/Tab.spec.tsx
  components/SubmissionsTable/Tab.tsx
  components/SubmissionsTable/index.module.scss
  components/SubmissionsTable/index.spec.tsx
  components/SubmissionsTable/index.tsx
  components/Tabs/Tabs.module.scss
  factories/submissions.ts
  pages/my-records.tsx
  pages/my-work.tsx
  pages/work-in-progress.tsx
  stylesheets/Section.module.scss
  stylesheets/all.scss
Labels: assessing and recording, enhancement, managing workloads, understanding residents

#622 fix(sct-919): preserve newlines in flexible answers
  components/FlexibleAnswers/FlexibleAnswers.module.scss
Labels: assessing and recording, enhancement

#625 fix(sct-857): auto save stuck on hidden conditionals
  components/Cases/CaseLink.spec.tsx
  components/Cases/__snapshots__/CaseLink.spec.tsx.snap
  components/FlexibleForms/FlexibleFields.spec.tsx
  components/FlexibleForms/FlexibleFields.tsx
  components/FlexibleForms/StepForm.tsx
  components/SubmissionsTable/SubmissionPanel.spec.tsx
  data/flexibleForms/adultCaseNote.ts
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/faceOverview.ts
  data/flexibleForms/foo.ts
  data/flexibleForms/forms.types.ts
  data/flexibleForms/review3C.ts
  data/flexibleForms/sgAdultConcern.ts
  data/flexibleForms/sgAdultManagerDecisionConcern.ts
  lib/notify.spec.ts
  lib/validators.spec.ts
  lib/validators.ts
Labels: assessing and recording, bug

#627 fix: canonical submission urls on the dashboard
  components/NewPersonView/UnfinishedSubmissions.tsx
  components/SubmissionsTable/SubmissionDetailDialog.spec.tsx
  components/SubmissionsTable/SubmissionDetailDialog.tsx
  components/SubmissionsTable/SubmissionPanel.tsx
  lib/submissions.spec.ts
  lib/submissions.ts
Labels: assessing and recording, bug

#629 fix(SCT-946): reload after approval, panel approval or reject
  components/ApprovalWidget/ApproveDialog.spec.tsx
  components/ApprovalWidget/ApproveDialog.tsx
  components/ApprovalWidget/PanelApproveDialog.spec.tsx
  components/ApprovalWidget/PanelApproveDialog.tsx
  components/ApprovalWidget/RejectDialog.spec.tsx
  components/ApprovalWidget/RejectDialog.tsx
Labels: assessing and recording, bug, enhancement
