Repository LBHackney-IT/lbh-social-care-frontend, pull requests merged in 2021-08, with the labels that each got.

#626 fix: add form data to submissions earlier on, so we can search on it
  components/SubmissionsTable/SubmissionPanel.spec.tsx
  components/SubmissionsTable/SubmissionPanel.tsx
  components/SubmissionsTable/index.spec.tsx
  components/SubmissionsTable/index.tsx
  data/flexibleForms/forms.types.ts
Labels: assessing and recording, bug

#653 Fix (Sct 994): Case notes date validation
  data/flexibleForms/adultCaseNote.ts
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/forms.types.ts
  lib/validators.ts
Labels: enhancement

#663 fix: make child case note text box larger
  data/flexibleForms/childCaseNote.ts
  data/flexibleForms/forms.types.ts
Labels: enhancement, assessing and recording
